import { PrismaClient, Role, TowRequestStatus, TowerAvailabilityStatus, DestinationType, TowRequest, User, Car, Destination, Tower } from './generated/prisma'; // Use generated client
import bcrypt from 'bcrypt';
import { v4 as uuidv4 } from "uuid"; // Keep for potential future use if needed, but Prisma handles IDs

// Re-export types generated by Prisma if needed elsewhere, or import directly from generated client
export type { User, Car, TowRequest, Tower, Destination } from './generated/prisma';
export { Role, TowRequestStatus, TowerAvailabilityStatus, DestinationType };

const prisma = new PrismaClient();
const saltRounds = 10; // Define salt rounds for bcrypt

// --- User CRUD operations ---
export const createUser = async (user: Omit<User, "userID" | "createdAt" | "updatedAt" | "cars" | "towRequests" | "towers" | "destinations">): Promise<User> => {
  const hashedPassword = await bcrypt.hash(user.passwordHash, saltRounds); // Hash password before saving
  return prisma.user.create({
    data: {
      ...user,
      passwordHash: hashedPassword,
    },
  });
};

export const getUserById = async (userID: string): Promise<User | null> => {
  return prisma.user.findUnique({
    where: { userID },
  });
};

export const getUserByEmail = async (email: string): Promise<User | null> => {
  return prisma.user.findUnique({
    where: { email },
  });
};

export const updateUser = async (userID: string, updates: Partial<Omit<User, "userID" | "createdAt" | "updatedAt" | "passwordHash">>): Promise<User | null> => {
  // Exclude passwordHash from direct updates here for security; handle password changes separately if needed
  return prisma.user.update({
    where: { userID },
    data: updates,
  });
};

// Example function for password update
export const updateUserPassword = async (userID: string, newPassword: string): Promise<User | null> => {
    const hashedPassword = await bcrypt.hash(newPassword, saltRounds);
    return prisma.user.update({
        where: { userID },
        data: { passwordHash: hashedPassword },
    });
};


export const deleteUser = async (userID: string): Promise<User | null> => {
  try {
    return await prisma.user.delete({
      where: { userID },
    });
  } catch (error) {
    // Handle specific Prisma errors, e.g., P2025 (Record not found)
    console.error(`Error deleting user ${userID}:`, error);
    return null; // Indicate deletion failed or record not found
  }
};

// --- Car CRUD operations ---
// Note: Prisma handles ID generation automatically
export const createCar = async (car: Omit<Car, "carID" | "createdAt" | "updatedAt" | "towRequests">): Promise<Car> => {
  return prisma.car.create({
    data: car,
  });
};

export const getCarById = async (carID: string): Promise<Car | null> => {
  return prisma.car.findUnique({
    where: { carID },
  });
};

export const getCarsByUserId = async (userID: string): Promise<Car[]> => {
  return prisma.car.findMany({
    where: { userID },
  });
};

export const updateCar = async (carID: string, updates: Partial<Omit<Car, "carID" | "createdAt" | "updatedAt" | "userID">>): Promise<Car | null> => {
  return prisma.car.update({
    where: { carID },
    data: updates,
  });
};

export const deleteCar = async (carID: string): Promise<Car | null> => {
   try {
    return await prisma.car.delete({
      where: { carID },
    });
  } catch (error) {
    console.error(`Error deleting car ${carID}:`, error);
    return null;
  }
};

// --- TowRequest CRUD operations ---
// Note: Prisma handles ID generation and relation connections
export const createTowRequest = async (request: Omit<TowRequest, "requestID" | "createdAt" | "updatedAt">): Promise<TowRequest> => {
  // Ensure related IDs are provided correctly in the input 'request' object
  // e.g., request.userID, request.carID, request.destinationID
  // Prisma connect syntax might be needed if connecting existing records
  return prisma.towRequest.create({
    data: {
      ...request,
      user: { connect: { userID: request.userID } }, // Connect to the user
      car: { connect: { carID: request.carID } }, // Connect to the car
      destination: { connect: { destinationID: request.destinationID } }, // Connect to the destination
      tower: request.towerID ? { connect: { towerID: request.towerID } } : undefined, // Optional connection
    },
  });
};

export const getTowRequestById = async (requestID: string): Promise<TowRequest | null> => {
  return prisma.towRequest.findUnique({
    where: { requestID },
    include: { // Include related data if needed
        requester: true,
        car: true,
        destination: true,
        tower: true,
    }
  });
};

export const getTowRequestsByUserId = async (userID: string): Promise<TowRequest[]> => {
  return prisma.towRequest.findMany({
    where: { userID },
    include: { car: true, destination: true, tower: true }, // Include related data
    orderBy: { requestTime: 'desc' } // Example ordering
  });
};

export const getTowRequestsByTowerId = async (towerID: string): Promise<TowRequest[]> => {
  return prisma.towRequest.findMany({
    where: { towerID },
     include: { requester: true, car: true, destination: true }, // Include related data
     orderBy: { requestTime: 'desc' }
  });
};

export const updateTowRequest = async (requestID: string, updates: Partial<Omit<TowRequest, "requestID" | "createdAt" | "updatedAt" | "userID" | "carID" | "destinationID">>): Promise<TowRequest | null> => {
  // Handle potential updates to relations separately if needed (e.g., changing towerID)
  return prisma.towRequest.update({
    where: { requestID },
    data: {
        ...updates,
        // Example: Handle tower assignment/update
        ...(updates.towerID && { tower: { connect: { towerID: updates.towerID } } }),
        ...(updates.towerID === null && { tower: { disconnect: true } }), // Handle unassignment
    },
  });
};

export const deleteTowRequest = async (requestID: string): Promise<TowRequest | null> => {
  try {
    return await prisma.towRequest.delete({
      where: { requestID },
    });
  } catch (error) {
    console.error(`Error deleting tow request ${requestID}:`, error);
    return null;
  }
};

// --- Tower CRUD operations ---
export const createTower = async (tower: Omit<Tower, "towerID" | "createdAt" | "updatedAt" | "towRequests">): Promise<Tower> => {
  return prisma.tower.create({
    data: {
        ...tower,
        user: { connect: { userID: tower.userID } } // Connect to the managing user
    },
  });
};

export const getTowerById = async (towerID: string): Promise<Tower | null> => {
  return prisma.tower.findUnique({
    where: { towerID },
    include: { user: true } // Include managing user
  });
};

export const getTowerByUserId = async (userID: string): Promise<Tower | null> => {
  // Assuming a one-to-one or one-to-many relation where a user manages a tower profile
  return prisma.tower.findFirst({ // Use findFirst if a user might manage multiple or none
    where: { userID },
    include: { user: true }
  });
};

export const updateTower = async (towerID: string, updates: Partial<Omit<Tower, "towerID" | "createdAt" | "updatedAt" | "userID">>): Promise<Tower | null> => {
  return prisma.tower.update({
    where: { towerID },
    data: updates,
  });
};

export const deleteTower = async (towerID: string): Promise<Tower | null> => {
  try {
    return await prisma.tower.delete({
      where: { towerID },
    });
  } catch (error) {
    console.error(`Error deleting tower ${towerID}:`, error);
    return null;
  }
};

// --- Destination CRUD operations ---
export const createDestination = async (destination: Omit<Destination, "destinationID" | "createdAt" | "updatedAt" | "towRequests">): Promise<Destination> => {
  return prisma.destination.create({
    data: {
        ...destination,
        managedBy: { connect: { userID: destination.userID } } // Connect to the managing user
    },
  });
};

export const getDestinationById = async (destinationID: string): Promise<Destination | null> => {
  return prisma.destination.findUnique({
    where: { destinationID },
    include: { managedBy: true } // Include managing user
  });
};

export const getDestinationsByType = async (type: DestinationType): Promise<Destination[]> => {
  return prisma.destination.findMany({
    where: { type },
    include: { managedBy: true }
  });
};

export const getDestinationsByUserId = async (userID: string): Promise<Destination[]> => {
  return prisma.destination.findMany({
    where: { userID },
    include: { managedBy: true }
  });
};

export const updateDestination = async (destinationID: string, updates: Partial<Omit<Destination, "destinationID" | "createdAt" | "updatedAt" | "userID">>): Promise<Destination | null> => {
  return prisma.destination.update({
    where: { destinationID },
    data: updates,
  });
};

export const deleteDestination = async (destinationID: string): Promise<Destination | null> => {
   try {
    return await prisma.destination.delete({
      where: { destinationID },
    }); 
  } catch (error) {
    console.error(`Error deleting destination ${destinationID}:`, error);
    return null;
  }
};

// Remove the mock database initialization
// initializeDatabase() // Remove this line
